# Development broker: TLS only, username/password required.
# Certificates and the password file are created by the "pki" service.

persistence false
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

listener 8883
cafile /pki/ca.pem
certfile /pki/server.pem
keyfile /pki/server.key
password_file /pki/passwd
allow_anonymous false
